### ISSUE TITLE
Entity sensor.cooktop_total_daily_energy from integration ldata has state class total_increasing, but its state is not strictly increasing

### ISSUE THREAD

**Issue by cyaneous** [rwoldberg/ldata-ha#28]
I am seeing this for a lot of sensors:

Entity sensor.cooktop_total_daily_energy from integration ldata has state class total_increasing, but its state is not strictly increasing. Triggered by state 0.16 (0.17) with last_updated set to 2024-12-26T00:24:19.401764+00:00. Please create a bug report at https://github.com/rwoldberg/ldata-ha/issues

They do indeed show up negative sometimes - the same is visible on the Leviton app. I am using the LDATA hub.

Would be nice to somehow avoid this in the log, perhaps an option to filter out negative values or report them as zero?

**Comment by rwoldberg** [comment]
Are you saying that the current watts is showing negative even on the app?  Have you asked Leviton about this?

**Comment by cyaneous** [comment]
I’ve just contacted them. Will report updates.On Dec 26, 2024, at 6:37 AM, Robert ***@***.***> wrote:﻿
Are you saying that the current watts is showing negative even on the app?  Have you asked Leviton about this?

**Comment by rwoldberg** [comment]
Interesting.  If they say this is expected and nothing is wrong, then I will add a filter to strip out negative values.

**Comment by cyaneous** [comment]
I still haven’t got an answer from them, but I do suspect this is normal for example in the case of solar or a generator - the breaker would then report a negative value.

**Comment by rwoldberg** [comment]
I would think that only the grid power CT could be negative.  I would think the power output on any of the others would always be positive.  But it looks like you have other breakers that are reporting negative values, correct?  Unless your cooktop is one of the new induction cooktops that also has a battery.

**Comment by cyaneous** [comment]
Yes, that's correct. It is an induction cooktop, but I am not aware of any battery. I have also seen it report negative on other circuits like lighting or a water heater. I do think in these cases it's a bug in the firmware, but regardless it looks like there is a good chance that these values can be negative for various reasons - ie. a bug, an incorrect measurement or a correct measurement for a generator/solar/etc breaker. Is it possible to just allow negative values? Ie. not set it as increasing only?

**Comment by rwoldberg** [comment]
I believe the total_daily_energy sensors have to be always increasing.  I'll modify the code to ignore negative values, but I still think there might be something wrong with your system, I don't know why the values would ever be negative.

**Comment by rwoldberg** [comment]
I have set the daily usage sensors to ignore negative values.

**Comment by cyaneous** [comment]
Oddly, the issue persists - still seeing negative value errors with the latest version.

Entity sensor.water_heater_1_total_daily_energy from integration Idata has state class total _increasing, but its state is not strictly increasing. Triggered by state 0.75 (0.76) with last_updated set to 2025-02-0309:55:52.199817+00:00. Please create a bug report at ht...

Entity sensor.cooktop_total_daily_energy from integration Idata has state class total_increasing, but its state is negative. Triggered by state -0.01 with last_updated set to 2025-02-03T04:42:44.353395+00:00. Please create a bug report at https://github.com/rwoldb...

**Comment by rwoldberg** [comment]
1.1.17 should fix the issue.

**Comment by cyaneous** [comment]
It appears the issue is still there:

Entity sensor.water_heater_1_total_daily_energy from integration ldata has state class total_increasing, but its state is negative. Triggered by state -0.01 with last_updated set to 2025-02-16T09:40:00.408529+00:00. Please create a bug report at https://github.com/rwoldberg/ldata-ha/issues

**Comment by cyaneous** [comment]
I think the fix needs to be applied to LDATADailyUsageSensor as well:

```
                if new_data is not None:
                    current_value = new_data["power"]
                # Make sure values are **positive** floats
                try:
                    **current_value = max(float(current_value), 0.0)**
                except ValueError:
                    current_value = 0
```

**Comment by rwoldberg** [comment]
Yes.  I have made that change, I just have not had time to push the code yet, I have been out of town and very busy.

**Comment by cyaneous** [comment]
Awesome, thanks!
